config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#root'
  scope '/admin' do
    
    # index of
    get "/", to: 'users#show', as: 'show_user'
    
    # links path
    resources :links
    
    # edit
    get "edit", to: 'users#edit', as: 'edit_user'
    patch "edit", to: 'users#update'
    
    # register
    get 'register', to: 'users#new', as: 'register'
    post 'register', to: 'users#create'
    
    # login
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    
    # logout
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'verify/:id', to: 'users#verify', as: 'verify'
    
  end

  get "l/:id", to: "links#goto", as: "goto"
  get "/:username", to: "links#api", as: "api"


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true,email: true
  validates :username, presence: true, uniqueness: true
  has_many :links

  def status_human  
    case self.status
    when 0
      I18n.t("active_account.disable")
    when 1
      I18n.t("active_account.active")
    else
      "Unknown"
    end
  end

  def time_of_expire
    nowDate = Time.zone.now
    expireDate = self.expired_at
    compareDate =  (expireDate - nowDate).ceil(0)
    message = "days ago expired"
    dateOf = compareDate / 86400 if compareDate 
    if compareDate > 0
      message = "next #{dateOf} days"
    elsif compareDate == 0
      message = "today"
    elsif compareDate < 0
      message = "#{dateOf.abs} days ago"
    end
    return message
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_authentication, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          session[:user_id] = @user.id
          UserMailer.with(user: @user).signup.deliver_later
          format.html { redirect_to "/admin", notice: I18n.t('notice.success_user') }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params_edit)
        format.html { redirect_to show_user_path , notice: t('notice.success_update_user') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def verify
    email = URI.decode(params[:email])
    id = params[:id]
    secrets = Rails.application.secrets[:secret_key_base]
    key = email + secrets
    sha2 = Digest::SHA2.new(256).hexdigest key
    if id == sha2
      user = User.find_by(email: email)
      if user.status == 0
        user.status = 1
        user.save()
        redirect_to "/admin/login", notice: t('notice.account_active')
      else
        redirect_to "/admin/login", notice: t('notice.wasActive')
      end
    else
      redirect_to "/admin/login", notice: t('notice.wrong_active_code')
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
    end

    # check use has access to this data or not
    def check_authentication
      unless session[:user_id]
        session[:user_id] = nil
        redirect_to "/admin/login", notice: t('notice.ask_login') 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation)
    end

    def user_params_edit
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :expired_at %>
    <%= form.datetime_select :expired_at %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_formEdit.html.erb
<%= form_with(model: user,url: "#",local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email, t('label.email') %>
    <input readonly="readonly" type="text" value="<%= user.email %>" id="user_email">
  </div>

  <div class="field">
    <%= form.label :username, t('label.username') %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password, t('label.password') %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, t('label.passwordConfirm') %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit t('button.updateUser')  %>
  </div>
<% end %>

app/views/users/_formRegister.html.erb
<%= form_with(model: user,url: "#",local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email, t('label.email') %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :username, t('label.username') %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password, t('label.password') %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, t('label.passwordConfirm') %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit t('button.createUser') %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('title.editUser') %></h1>

<%= render 'formEdit', user: @user %>

<%= link_to t('button.back'), show_user_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Status</th>
      <th>Expired at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.status %></td>
        <td><%= user.expired_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1><%= t('title.newUser') %></h1>

<%= render 'formRegister', user: @user %>

app/views/users/show.html.erb
<h1>
  <%= t('title.home') %>
  <small>[<%= link_to t('button.edit'), edit_user_path %>]</small>  
</h1>
<p>
  <strong><%= t('label.page') %>:</strong>
  <%= link_to api_url(@user.username) ,api_url(@user.username) %>
</p>
<p>
  <strong><%= t('label.email') %>:</strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= t('label.username') %>:</strong>
  <%= @user.username %>
</p>

<p>
  <strong><%= t('label.status') %>:</strong>
  <%= @user.status_human %>
</p>