config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#root'
  scope '/admin' do
    
    # index of
    get "/", to: 'users#show', as: 'show_user'
    
    # links path
    resources :links
    
    # edit
    get "edit", to: 'users#edit', as: 'edit_user'
    patch "edit", to: 'users#update'
    
    # register
    get 'register', to: 'users#new', as: 'register'
    post 'register', to: 'users#create'
    
    # login
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    
    # logout
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'verify/:id', to: 'users#verify', as: 'verify'
    
  end

  get "l/:id", to: "links#goto", as: "goto"
  get "/:username", to: "links#api", as: "api"


end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :analytics
  validates :title, presence: true,length: { minimum: 4 }
  validates :url,presence: true, length: { minimum: 4, max: 1745 }, url: true
  default_scope { order('created_at ASC') }

  before_create do
    self.uuid = UUIDTools::UUID.random_create
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :checkUser, except: [:goto, :addToAnalytics, :api ]  
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.where(user_id: current_user.id)
  end

  # GET /links/1
  # GET /links/1.json
  def show
    nowTime = Time.now
    fiveDayAgo = nowTime - 5.days
    @thisTime = fiveDayAgo()
    @analytic = Analytic.where(link_id: @link.id, user_id: @current_user.id)
                        .where("created_at >= ?", fiveDayAgo)
                        .to_json(:except => [:id,:link_id, :user_id,:updated_at])
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)
    authorize @link
    respond_to do |format|
      if @link.save
        format.html { redirect_to link_path(@link.uuid), notice: t('notice.success_create_link') }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    authorize @link
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_path(@link.uuid), notice: t('notice.success_update_link') }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: t('notice.success_destroy_link') }
      format.json { head :no_content }
    end
  end


  def goto
    link = Link.find_by(uuid: params[:id])
    begin
      redirect_to link.url, status: 301
      use_link(link.url)
      addToAnalytics(link)
    rescue => exception
      render plain: exception
    end
  end

  def api
    begin
      @user = User.find_by!(username: params[:username])
      @links = @user.links
      render :api, layout: "linksPage"
    rescue
      redirect_to "/"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find_by(uuid: params[:id])
    end

    def fiveDayAgo
      days = Array.new
      now = Time.now
      days << now.to_f * 1000
      puts "salam"
      for dd in (1...5)
        newDays = now - dd.days
        convertDays = newDays.to_f * 1000
        days << convertDays
      end
      return days.to_json
    end

    def use_link(link)
      client = DeviceDetector.new(request.user_agent)
      splitUrl = URI.split(link)
      p "#{splitUrl[2]} #{client.device_type} #{client.device_name}"
    end

    def addToAnalytics(linkModel)
      client = DeviceDetector.new(request.user_agent)
      anal = Analytic.new
      anal.ip = request.remote_ip
      anal.link_id = linkModel.id
      anal.user_id = linkModel.user_id
      anal.device = client.device_name
      anal.device_type= client.device_type
      anal.os= client.os_name
      anal.browser= client.name
      anal.async.save()
    end

    def checkUser
      unless current_user
        session[:user_id] = nil
        redirect_to "/admin/login", notice: t('notice.ask_login')
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uuid %>
    <%= form.text_field :uuid %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :isEnabled %>
    <%= form.number_field :isEnabled %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :isHighlight %>
    <%= form.number_field :isHighlight %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_formEdit.html.erb
<%= form_with(url: link_path(link.uuid), model: link , local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title, t('label.title') %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url, t('label.url') %>
    <%= form.url_field :url %>
  </div>

  <div class="actions">
    <%= form.submit t('button.updateLink') %>
  </div>
<% end %>

app/views/links/_formNew.html.erb
<%= form_with( model: link , local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title, t('label.title') %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url, t('label.url') %>
    <%= form.url_field :url %>
  </div>

  <div class="actions">
    <%= form.submit t('button.createLink') %>
  </div>
<% end %>

app/views/links/api.html.erb
<div id="wrapper">
    <% @links.each do |link| %>
        <h2><%= link_to link.title, goto_path(link.uuid) %></h2>
    <% end %>
    <div id="copy">
        <p>
            ساخته شده با 
            <%= link_to t('title.name'), root_url %>
            به سفارش
             <%= link_to @user.username, api_url(@user.username) %> 

        </p>
    </div>
</div>

app/views/links/edit.html.erb
<h1><%= t('title.editLink') %></h1>

<%= render 'formEdit', link: @link %>

<%= link_to t('button.show'), link_path(@link.uuid) %> |
<%= link_to t('button.back'), links_path %>

app/views/links/index.html.erb
<h1>
  <%= t('title.links') %>
  <small>[<%= link_to t('button.newLink'), new_link_path %>]</small>  
</h1>

<table>
  <thead>
    <tr>
      <th><%= t('th.number') %></th>
      <th><%= t('th.title') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% cnt = 1 %>
    <% @links.each do |link| %>
      <tr>
        <td><%= cnt %></td>
        <td><%= link.title %></td>
        <td><%= link_to t('button.analytics'), link_path(link.uuid)  %></td>
        <td><%= link_to t('button.edit'), edit_link_path(link.uuid) %></td>
        <td><%= link_to t('button.destroy'), link_path(link.uuid), method: :delete, data: { confirm: t('alert.confirm') } %></td>
        <% cnt += 1 %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/links/new.html.erb
<h1><%= t('title.newLink') %></h1>

<%= render 'formNew', link: @link %>

<%= link_to t('button.back'), links_path %>

app/views/links/show.html.erb
<p>
  <strong><%= t('label.title') %>:</strong>
  <%= @link.title %>
</p>
<p>
  <strong><%= t('label.url') %>:</strong>
  <span style="display: inline-block; direction: ltr; text-align: left"><%= URI.decode @link.url %></span>
</p>
<%= link_to t('button.edit'), edit_link_path(@link.uuid) %> |
<%= link_to t('button.back'), links_path %>
<div class="chart-container">
    <canvas id="myChart"></canvas>
</div>



<script>
  var data = <%= @analytic.html_safe %>;
  var serverFiveDays = <%= @thisTime.html_safe %>;
  function formatDateOf(days){
    var result = [];
    days.forEach(element => {
      var dateOf = new Date(element);
      result.push(`${dateOf.getFullYear()}/${dateOf.getMonth()}/${dateOf.getDate()}`);
    });
    return result;
  }
  var fiveDays = formatDateOf(serverFiveDays);
  var gData = _u.groupBy(data, function(item){
    var times = new Date(item.created_at);
    return `${times.getFullYear()}/${times.getMonth()}/${times.getDate()}`
  });
  var uniqArray = _u.difference(fiveDays, Object.keys(gData));
  uniqArray.forEach(element => {
      gData[element] = [];
  });
var sDate = Object.keys(gData).sort().reduce((accumulator, currentValue) => {
  accumulator[currentValue] = gData[currentValue];
  return accumulator;
}, {});
var dataArray = _u.map(Object.values(sDate), function(item){
  return item.length
});

  var ctx = $('#myChart');
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      datasets: [{
            label: 'page view',
            data:dataArray,
            borderColor: "#CBE4F5",
            backgroundColor: "#0539B7",
            borderWidth: 4,
            pointBorderWidth: 10,
            fill:false
        }],
        labels: Object.keys(sDate)
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true,
                    precision: 0,
                    suggestedMax: 10
                }
            }]
        },
      elements: {
            line: {
                tension: 0
            }
        }
    }
});
</script>